wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: Pointnet++
dataset:
  desc: null
  value: MN40
_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683867579.429951
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.7.6
      5: 0.15.2
      8:
      - 5
